language: cpp

os: osx

before_install:
  - brew install llvm

jobs:
  include:
    - script: /bin/bash build_deps.sh
    - script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ../ && make
